name: Deploy to Surge

on:
  workflow_dispatch:        # Run button
  push:
    branches: [ main ]      # Deploy on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOMAIN: dmhshows.surge.sh     # <-- put YOUR Surge domain
      DEPLOY_DIR: ./public          # <-- use ./ if index.html is at repo root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (diagnostic)
        run: |
          echo "PWD = $PWD"
          ls -la
          echo "---- $DEPLOY_DIR ----"
          ls -la "$DEPLOY_DIR" || true

      - name: Verify site folder exists
        run: |
          if [ ! -d "$DEPLOY_DIR" ]; then
            echo "::error::DEPLOY_DIR $DEPLOY_DIR not found. Set DEPLOY_DIR=./ or create public/"
            exit 1
          fi
          if [ ! -f "$DEPLOY_DIR/index.html" ]; then
            echo "::error::No index.html in $DEPLOY_DIR"
            exit 1
          fi

      - name: Install Surge CLI
        run: npm i -g surge

      - name: Deploy to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          echo "Deploying $DEPLOY_DIR -> https://$DOMAIN"
          npx surge "$DEPLOY_DIR" "$DOMAIN" --token "$SURGE_TOKEN"
